last_shot_and_timelapse_suid_wrapper: last_shot_and_timelapse_suid_wrapper.c
	gcc -o ../last_shot_and_timelapse_suid_wrapper last_shot_and_timelapse_suid_wrapper.c

light_control_suid_wrapper: light_control_suid_wrapper.c
	gcc -o ../light_control_suid_wrapper light_control_suid_wrapper.c

light_stop_suid_wrapper: light_stop_suid_wrapper.c
	gcc -o ../light_stop_suid_wrapper light_stop_suid_wrapper.c

reboot_suid_wrapper: reboot_suid_wrapper.c
	gcc -o ../reboot_suid_wrapper reboot_suid_wrapper.c
	
shutdown_suid_wrapper: shutdown_suid_wrapper.c
	gcc -o ../shutdown_suid_wrapper shutdown_suid_wrapper.c


all:
	gcc -o ../last_shot_and_timelapse_suid_wrapper last_shot_and_timelapse_suid_wrapper.c
	gcc -o ../light_control_suid_wrapper light_control_suid_wrapper.c
	gcc -o ../light_stop_suid_wrapper light_stop_suid_wrapper.c
	gcc -o ../reboot_suid_wrapper reboot_suid_wrapper.c
	gcc -o ../shutdown_suid_wrapper shutdown_suid_wrapper.c
